Document: gtklantetris
Title: Debian gtklantetris Manual
Author: <insert document author here>
Abstract: This manual describes what gtklantetris is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gtklantetris/gtklantetris.sgml.gz

Format: postscript
Files: /usr/share/doc/gtklantetris/gtklantetris.ps.gz

Format: text
Files: /usr/share/doc/gtklantetris/gtklantetris.text.gz

Format: HTML
Index: /usr/share/doc/gtklantetris/html/index.html
Files: /usr/share/doc/gtklantetris/html/*.html

  
